# https://github.com/mbj/mutant/blob/master/docs/configuration.md

usage: opensource
requires:
  - pg_objects
includes:
  - lib
integration:
  name: rspec
mutation:
  operators: light
coverage_criteria:
  process_abort: true
# matcher:
#   subjects:
#     - PgObjects*
