name: Build and Publish Gem

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    # Set up
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ruby

    # Update version from release tag
    - name: Update version from release tag
      run: |
        TAG_NAME="${{ github.event.release.tag_name }}"
        # Remove 'v' prefix if it exists
        VERSION="${TAG_NAME#v}"
        echo "Setting version to: $VERSION"
        sed -i "s/VERSION = '.*'/VERSION = '$VERSION'/" lib/pg_objects/version.rb
        cat lib/pg_objects/version.rb

    # Release
    - uses: rubygems/release-gem@v1
