name: Build and Publish Gem

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch tags
      run: git fetch --tags

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: false
        ruby-version: ruby

    - name: Install dependencies
      run: |
        bundle config set --local frozen false
        bundle install

    - name: Release gem
      uses: rubygems/release-gem@v1
