name: Start Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g., 1.5.0)'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  start-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release branch
        run: |
          git checkout -b release/v${{ github.event.inputs.version }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Update version.rb
        run: |
          sed -i "s/VERSION = '.*'/VERSION = '${{ github.event.inputs.version }}'/" lib/pg_objects/version.rb
          echo "Updated version.rb to ${{ github.event.inputs.version }}"
          cat lib/pg_objects/version.rb

      - name: Install dependencies and update Gemfile.lock
        run: bundle install

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lib/pg_objects/version.rb Gemfile.lock
          git commit -m "Bump version to ${{ github.event.inputs.version }} [release]"
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump version to ${{ github.event.inputs.version }} [release]"
          branch: release/v${{ github.event.inputs.version }}
          title: "Release v${{ github.event.inputs.version }}"
          body: |
            Automated version bump to **v${{ github.event.inputs.version }}**.
            
            This PR updates:
            - `lib/pg_objects/version.rb`
            - `Gemfile.lock`
            
            Auto-merge is enabled.
          base: master
          add-paths: |
            lib/pg_objects/version.rb
            Gemfile.lock
          delete-branch: true
          labels: |
            release
            automated 